name: 02-Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        default: "0.1"
        required: false
      quality:
        description: "Quality level"
        default: "rc"
        required: false
jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate tag
        id: calculate-tag
        run: |
          build_number="$(date +'%m%d%H%M')"
          new_tag=v${{ github.event.inputs.version }}-${{ github.event.inputs.quality }}-${build_number} # e.g. v0.1-rc-101012
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
          echo "release_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.calculate-tag.outputs.new_tag }}
          release_date: ${{ steps.calculate-tag.outputs.release_date }}
          release_name: ${{ steps.calculate-tag.outputs.new_tag }} - ${{ steps.calculate-tag.outputs.release_date }}
          draft: false
          prerelease: true
          body: |
            # Enhancements

            - Add new feature X

            # Bug fixes

            - Fix issue Y

            # Breaking changes

            - Remove feature Z

            # Known issues

            - No known issues
