name: 02-Create release

on:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the previous release tag
        id: prev-tag
        run: |
          prev_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=prev_tag::$prev_tag"

      - name: Calculate new tag
        id: new-tag
        run: |
          prev_tag=${{ steps.prev-tag.outputs.prev_tag }}
          if [[ $prev_tag =~ ^v0\.1-beta\.([0-9]+)$ ]]; then
            new_tag=v0.1-beta.$((BASH_REMATCH[1]+1))
          else
            new_tag=v0.1-beta.1
          fi
          echo "::set-output name=new_tag::$new_tag"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.new-tag.outputs.new_tag }}
          release_name: ${{ steps.new-tag.outputs.new_tag }} $(date +'%Y-%m-%d')
          draft: false
          prerelease: true
          body: |
            Changes since ${{ steps.prev-tag.outputs.prev_tag }}:
            $(git log --pretty=format:"%h %s" ${{ steps.prev-tag.outputs.prev_tag }}..HEAD)
