name: 02-Create release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate tag
        id: new-tag
        run: |
          new_tag=v0.1-beta.$(date +'%m%d%H%M')
          echo "::set-output name=new_tag::$new_tag"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.new-tag.outputs.new_tag }}
          release_name: ${{ steps.new-tag.outputs.new_tag }} $(date +'%Y-%m-%d')
          draft: false
          prerelease: true
          body: |
            Changes since ${{ steps.prev-tag.outputs.prev_tag }}:
            $(git log --pretty=format:"%h %s" ${{ steps.prev-tag.outputs.prev_tag }}..HEAD)
